# Generated by Django 3.0.3 on 2020-03-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ativo',
            new_name='active',
        ),
    ]
